spring:
  application:
    name: springbootApp
  profiles:
    active: prod
  mvc:
    servlet:
      path: /api
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kishor182256/cloudConfig

jwt:
  secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf
  validity: 18000

