spring:
  mvc:
    servlet:
      path: /api

#  datasource:
#    url:  jdbc:postgresql://localhost:5432/springboot
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#  jpa:
#    database: postgresql
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        hibernate:
#          ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - flyway
          - beans
          - env
          - loggers
          - shutdown
  endpoint:
    health:
      show-details: always
    info:
      access:
  info:
    env:
      enabled: true

info:
  app:
    name: SpringBootApp
    version: 1.0.0
    description: Spring Boot application with H2 and Actuator

